package impl;

import java.util.HashMap;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * 
 * @author mohsherif
 *
 */
public class FindTheDifference {
	
	public char findTheDifference(String s, String t) {
		HashMap<Character, Integer> smap = new HashMap<Character, Integer>();
		HashMap<Character, Integer> tmap = new HashMap<Character, Integer>();
		
		for (int i = 0; i < s.length(); i++) {
			if(!smap.containsKey(s.charAt(i))){
				smap.put(s.charAt(i), 1);
			}else{
				smap.put(s.charAt(i), (smap.get(s.charAt(i)) +1));
			}
		}
		
		for (int i = 0; i < t.length(); i++) {
			if(!tmap.containsKey(t.charAt(i))){
				tmap.put(t.charAt(i), 1);
			}else{
				tmap.put(t.charAt(i), (tmap.get(t.charAt(i)) +1));
			}
		}
		
		for (int i = 0; i < t.length(); i++) {
			if(!smap.containsKey(t.charAt(i))){
				return t.charAt(i);
			}else if(tmap.get(t.charAt(i)) > smap.get(t.charAt(i))){
				return t.charAt(i);
			}
		}
		return ' ';
	}
}
